id: A81122C02
title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
type: translation
pechas:
- IFB8678C7
- I86348A62
- I01D44952
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:08:46.815855
  last_modified_at: 2023-01-04 13:08:46.815860
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IFB8678C7/BF03: '8892'
  I86348A62/C81A: '8892'
  I01D44952/9133: '8892'
